/* IMO Premium V2 demo enhancements */
(function(){
const $=s=>document.querySelector(s); const C=()=>document.getElementById('content');
const oldStart=window.startApp||startApp;
USERS.admin.name='Ronaldo'; USERS.admin.initials='RO'; USERS.admin.context='Centro de Operações'; USERS.admin.meta='Imóvel em Ordem';
NAV.admin=[['OPERAÇÃO',[['dashboard','⌂','Centro de Operações'],['condominios','▣','Condomínios'],['contratos','◇','Contratos'],['incorporadoras','◆','Incorporadoras'],['atendimento','◉','Central de atendimento']]],['CONTEÚDO IMO',[['manuais','▤','Manuais do Proprietário'],['garantias','◒','Garantias'],['rotinas','↻','Planos de manutenção'],['documentos','⌑','Plantas & Databook']]],['PLATAFORMA',[['usuarios','◎','Usuários & acessos'],['configuracoes','⚙','Configurações']]]];
NAV.incorporadora[0][1].push(['atendimento','◉','Falar com IMO']); NAV.sindico[0][1].push(['atendimento','◉','Falar com incorporadora']); NAV.morador[1][1].push(['atendimento','◉','Falar com síndico']);
const condos=[
{name:'Residencial Noon',type:'Vertical',inc:'Alfa Realty',sind:'Ronaldo Oliveira',units:128,contract:'01/03/2024 → 28/02/2029',status:'ATIVO'},
{name:'Reserva Vila Mariana',type:'Vertical + Garden',inc:'Urban Incorporadora',sind:'Ana Martins',units:216,contract:'15/08/2023 → 14/08/2028',status:'ATIVO'},
{name:'Villas do Lago',type:'Casas',inc:'Horizonte Desenvolvimento',sind:'Paulo Mendes',units:84,contract:'01/01/2025 → 31/12/2029',status:'ATIVO'},
{name:'Parque das Araucárias',type:'Misto',inc:'Alfa Realty',sind:'Carla Souza',units:176,contract:'10/11/2022 → 09/11/2027',status:'RENOVAÇÃO'}];
const oldOpen=openPage; openPage=function(page){ if(currentUser==='admin'&&page==='dashboard'){prep(page,'Centro de Operações');renderAdmin();return} if(page==='condominios'){prep(page,'Condomínios');renderCondos();return} if(page==='contratos'){prep(page,'Contratos');renderContracts();return} if(page==='atendimento'){prep(page,'Central de atendimento');renderSupport();return} if(page==='manual'){prep(page,'Manual do proprietário');renderMagazine();return} oldOpen(page)}; window.openPage=openPage;
function prep(page,label){currentPage=page;document.querySelectorAll('.nav-item[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.getElementById('sidebar').classList.remove('open');document.getElementById('pageTitle').textContent=label;document.getElementById('breadcrumb').textContent=`IMO / ${USERS[currentUser].role} / ${label}`}
function renderAdmin(){C().innerHTML=`<div class="hero-premium"><div><p class="eyebrow">CENTRO DE OPERAÇÕES IMO</p><h1>${greeting()}, Ronaldo.</h1><p>Gestão executiva de clientes, contratos, conteúdo proprietário e operação da plataforma.</p></div><button class="action-btn primary" onclick="openWizard()">＋ Novo condomínio</button></div><div class="metrics">${metric('▣','12','Condomínios ativos','+2 este ano')}${metric('◇','11','Contratos vigentes','92% carteira')}${metric('⌛','2','Renovações próximas','120 dias')}${metric('◉','7','Atendimentos abertos','SLA 94%')}</div><div class="section-title">CARTEIRA DE CLIENTES</div>${condoTable()}<div class="premium-grid"><div class="panel"><div class="panel-header"><h3>Saúde da operação</h3><span>Agosto 2026</span></div><div class="health"><b>94%</b><div><strong>Excelente</strong><span>Contratos, implantação e atendimento dentro do esperado.</span></div></div><div class="mini-stats"><span><b>1.248</b> unidades</span><span><b>1.473</b> usuários</span><span><b>36</b> manuais</span></div></div><div class="panel"><div class="panel-header"><h3>Atenção executiva</h3><span>3 itens</span></div><div class="activity-list"><div class="activity"><div class="activity-dot">⌛</div><div><strong>Parque das Araucárias</strong><span>Renovação em 15 meses</span></div></div><div class="activity"><div class="activity-dot">▤</div><div><strong>Manual aguardando publicação</strong><span>Reserva Vila Mariana • versão 2026.3</span></div></div><div class="activity"><div class="activity-dot">◉</div><div><strong>2 chamados próximos do SLA</strong><span>Alfa Realty</span></div></div></div></div></div>`}
function condoTable(){return `<div class="panel table-panel"><div class="panel-header"><h3>Todos os condomínios</h3><span>${condos.length} exibidos na demonstração</span></div><div class="table-scroll"><table class="data-table"><thead><tr><th>Cliente</th><th>Tipologia</th><th>Incorporadora</th><th>Síndico</th><th>Unidades</th><th>Contrato</th><th>Status</th><th>Acessar como</th></tr></thead><tbody>${condos.map((x,i)=>`<tr><td><b>${x.name}</b></td><td>${x.type}</td><td>${x.inc}</td><td>${x.sind}</td><td>${x.units}</td><td>${x.contract}</td><td><span class="status ${x.status==='ATIVO'?'green':'yellow'}">${x.status}</span></td><td><button class="mini-btn" onclick="impersonate('incorporadora','${x.name}')">Incorporadora</button> <button class="mini-btn" onclick="impersonate('sindico','${x.name}')">Síndico</button></td></tr>`).join('')}</tbody></table></div></div>`}
function renderCondos(){C().innerHTML=`<div class="welcome-row"><div><p class="eyebrow">CARTEIRA IMO</p><h1>Condomínios</h1><p>Cada condomínio é um cliente, ligado à incorporadora, contrato, síndico e conteúdo técnico.</p></div><button class="action-btn primary" onclick="openWizard()">＋ Cadastrar condomínio</button></div>${condoTable()}`}
function renderContracts(){C().innerHTML=`<div class="welcome-row"><div><p class="eyebrow">GESTÃO COMERCIAL</p><h1>Contratos</h1><p>Ciclo completo do relacionamento comercial, implantação e renovação.</p></div><button class="action-btn primary" onclick="openWizard()">＋ Novo contrato</button></div><div class="metrics">${metric('◇','11','Vigentes','R$ 31,8 mil/mês')}${metric('⌛','2','Renovações','Próx. 120 dias')}${metric('◈','5 anos','Prazo médio','Carteira')}${metric('▣','1.248','Unidades contratadas','Ativas')}</div>${condoTable()}`}
function renderSupport(){const labels={admin:['Incorporadoras','Alfa Realty'],incorporadora:['Síndicos','Ronaldo Oliveira'],sindico:['Moradores','Matheus Prado'],morador:['Síndico','Ronaldo Oliveira']};const l=labels[currentUser];C().innerHTML=`<div class="welcome-row"><div><p class="eyebrow">COMUNICAÇÃO HIERÁRQUICA</p><h1>Central de atendimento</h1><p>Canal interno com histórico, protocolo e status.</p></div><button class="action-btn primary" onclick="toast('Novo atendimento iniciado')">＋ Novo chamado</button></div><div class="support-shell"><div class="panel tickets"><small>${l[0].toUpperCase()}</small><div class="ticket active"><b>${l[1]}</b><span>#IMO-1048 • Manual / implantação</span><em>2 novas</em></div><div class="ticket"><b>Atendimento #IMO-1039</b><span>Documentação técnica</span></div></div><div class="panel chat"><div class="chat-head"><div><b>${l[1]}</b><span>Protocolo #IMO-1048 • Em atendimento</span></div><span class="status green">ABERTO</span></div><div class="messages"><p><b>${l[1]}</b> Precisamos validar a nova versão do manual antes da publicação.</p><p class="mine"><b>Você</b> Perfeito. A versão 2026.3 já está em revisão e ficará vinculada ao condomínio.</p></div><div class="chat-input">Digite uma mensagem… <button onclick="toast('Mensagem enviada')">Enviar</button></div></div></div>`}
window.impersonate=function(role,condo){localStorage.setItem('imo_return_admin','1');startApp(role);document.getElementById('contextName').textContent=condo;document.getElementById('contextMeta').textContent='Visualização supervisionada';const top=document.querySelector('.topbar');let bar=document.getElementById('impersonationBar');if(!bar){bar=document.createElement('div');bar.id='impersonationBar';bar.className='impersonation-bar';top.parentNode.insertBefore(bar,top.nextSibling)}bar.innerHTML=`Você está visualizando <b>${condo}</b> como <b>${USERS[role].role}</b>. <button onclick="returnAdmin()">Voltar ao Super Admin</button>`};
window.returnAdmin=function(){localStorage.removeItem('imo_return_admin');const b=document.getElementById('impersonationBar');if(b)b.remove();startApp('admin')};
window.openWizard=function(){const m=document.createElement('div');m.className='modal-backdrop';m.id='wizard';m.innerHTML=`<div class="wizard"><button class="wizard-x" onclick="wizard.remove()">×</button><p class="eyebrow">NOVO CLIENTE • PASSO 1 DE 3</p><h2>Que tipo de condomínio vamos configurar?</h2><p class="muted">A tipologia sugere automaticamente áreas, módulos e estrutura inicial.</p><div class="type-grid">${[['🏢','Vertical','Prédio / torres'],['🏘','Horizontal','Condomínio de casas'],['◫','Misto','Prédios + casas'],['♧','Garden','Unidades garden / térreas']].map(x=>`<button onclick="wizardStep2('${x[1]}')"><b>${x[0]}</b><strong>${x[1]}</strong><span>${x[2]}</span></button>`).join('')}</div></div>`;document.body.appendChild(m)};
window.wizardStep2=function(type){document.querySelector('.wizard').innerHTML=`<button class="wizard-x" onclick="wizard.remove()">×</button><p class="eyebrow">NOVO CLIENTE • PASSO 2 DE 3</p><h2>${type}: configure as áreas</h2><p class="muted">Sugestões inteligentes. Ronaldo pode marcar ou remover qualquer item.</p><div class="amenities">${['Salão de festas','Churrasqueira','Piscina','Sauna','Academia','Quadra','Brinquedoteca','Coworking','Pet place','Bicicletário'].map((x,i)=>`<label><input type="checkbox" ${i<6?'checked':''}> ${x}</label>`).join('')}</div><button class="primary-btn wide" onclick="wizardStep3('${type}')">Continuar →</button>`};
window.wizardStep3=function(type){document.querySelector('.wizard').innerHTML=`<button class="wizard-x" onclick="wizard.remove()">×</button><p class="eyebrow">NOVO CLIENTE • PASSO 3 DE 3</p><h2>Contrato e implantação</h2><div class="form-grid"><label>Condomínio<input value="Residencial Horizonte"></label><label>Tipologia<input value="${type}" readonly></label><label>Incorporadora<select><option>Alfa Realty</option><option>Urban Incorporadora</option></select></label><label>Prazo<select><option>5 anos</option><option>3 anos</option></select></label><label>Início<input type="date" value="2026-08-13"></label><label>Unidades<input type="number" value="180"></label></div><div class="wizard-content"><b>Conteúdo IMO a implantar</b><label><input type="checkbox" checked> Manual do Proprietário</label><label><input type="checkbox" checked> Manual do Síndico</label><label><input type="checkbox" checked> Plano de manutenção</label><label><input type="checkbox" checked> Garantias</label><label><input type="checkbox" checked> Plantas & Databook</label></div><button class="primary-btn wide" onclick="toast('Condomínio configurado para demonstração');wizard.remove()">Criar condomínio e contrato ✓</button>`};
window.renderMagazine=function(){C().innerHTML=`<div class="welcome-row"><div><p class="eyebrow">CONTEÚDO PROTEGIDO IMO</p><h1>Manual do Proprietário</h1><p>Residencial Noon • versão 2026.2 • visualização controlada</p></div><span class="status green">PUBLICADO</span></div><div class="magazine-shell"><div class="mag-toolbar"><span>▤ Manual do Proprietário</span><div><button onclick="magPrev()">←</button><b id="pageNum">2–3 / 64</b><button onclick="magNext()">→</button></div><span>🔒 Visualização protegida</span></div><div class="magazine" id="magazine"><div class="page cover"><small>IMÓVEL EM ORDEM</small><h2>Manual do<br>Proprietário</h2><p>Residencial Noon</p><span>Versão 2026.2</span></div><div class="page"><small>02 • BOAS-VINDAS</small><h3>Seu imóvel, em ordem.</h3><p>Este manual reúne orientações de uso, conservação, manutenção e garantias da sua unidade.</p><div class="page-card">✓ Consulte sempre as orientações antes de qualquer intervenção.</div><p class="watermark">IMO • USO AUTORIZADO</p></div></div><p class="protected-note">Conteúdo autoral • sessão identificada • download desabilitado nesta demonstração</p></div>`};
let pg=2;window.magNext=()=>{pg=Math.min(62,pg+2);$('#pageNum').textContent=`${pg}–${pg+1} / 64`;$('#magazine').classList.add('flip');setTimeout(()=>$('#magazine').classList.remove('flip'),450)};window.magPrev=()=>{pg=Math.max(2,pg-2);$('#pageNum').textContent=`${pg}–${pg+1} / 64`};
})();